export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="scrollbar-none scrollbar-thumb-selected scrollbar-track-black " >{children}</body>
    </html>
  )
}
